# Generated by Django 5.2.4 on 2026-06-02 22:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0002_personalprefrences'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalprefrences',
            name='cycle_timeInSecond',
            field=models.PositiveIntegerField(blank=True, default=1500, null=True),
        ),
        migrations.AlterField(
            model_name='personalprefrences',
            name='session_timeInSecond',
            field=models.PositiveIntegerField(blank=True, default=5100, null=True),
        ),
        migrations.AlterField(
            model_name='personalprefrences',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
