# Generated by Django 6.1 on 2026-08-23 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0003_alter_personalprefrences_cycle_timeinsecond_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessiontimer',
            name='minute_amount',
            field=models.PositiveIntegerField(),
        ),
    ]
